/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodosNewRouteImport } from './routes/todos/new'
import { Route as TodosIdIndexRouteImport } from './routes/todos/$id/index'
import { Route as TodosIdEditRouteImport } from './routes/todos/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosNewRoute = TodosNewRouteImport.update({
  id: '/todos/new',
  path: '/todos/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosIdIndexRoute = TodosIdIndexRouteImport.update({
  id: '/todos/$id/',
  path: '/todos/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosIdEditRoute = TodosIdEditRouteImport.update({
  id: '/todos/$id/edit',
  path: '/todos/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/todos/new': typeof TodosNewRoute
  '/todos/$id/edit': typeof TodosIdEditRoute
  '/todos/$id': typeof TodosIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/todos/new': typeof TodosNewRoute
  '/todos/$id/edit': typeof TodosIdEditRoute
  '/todos/$id': typeof TodosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/todos/new': typeof TodosNewRoute
  '/todos/$id/edit': typeof TodosIdEditRoute
  '/todos/$id/': typeof TodosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/todos/new' | '/todos/$id/edit' | '/todos/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/todos/new' | '/todos/$id/edit' | '/todos/$id'
  id: '__root__' | '/' | '/todos/new' | '/todos/$id/edit' | '/todos/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TodosNewRoute: typeof TodosNewRoute
  TodosIdEditRoute: typeof TodosIdEditRoute
  TodosIdIndexRoute: typeof TodosIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/new': {
      id: '/todos/new'
      path: '/todos/new'
      fullPath: '/todos/new'
      preLoaderRoute: typeof TodosNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/$id/': {
      id: '/todos/$id/'
      path: '/todos/$id'
      fullPath: '/todos/$id'
      preLoaderRoute: typeof TodosIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/$id/edit': {
      id: '/todos/$id/edit'
      path: '/todos/$id/edit'
      fullPath: '/todos/$id/edit'
      preLoaderRoute: typeof TodosIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TodosNewRoute: TodosNewRoute,
  TodosIdEditRoute: TodosIdEditRoute,
  TodosIdIndexRoute: TodosIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
